stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - params.yaml
      - data/raw/Fraud_data.csv
    outs:
      - data/processed/fraud_data_processed.csv