stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - params.yaml
      - data/raw/Fraud_data.csv
    outs:
      - data/processed/fraud_data_processed.csv
  
  train_rf:
    cmd: python src/train_rf.py
    deps:
      - src/train_rf.py
      - src/mlflow_tracking.py
      - data/processed/Fraud_data_processed.csv
      - params.yaml
    outs:
      - models/rf_model.pkl

  evaluate_rf:
    cmd: python src/evaluate_rf.py
    deps:
      - src/evaluate_rf.py
      - data/processed/fraud_data_processed.csv
      - models/rf_model.pkl
    metrics:
      - metrics/rf_metrics.json