# params.yaml
data:
  raw_path: 'data/raw/Fraud_data.csv'
  processed_dir: data/processed
  processed_file: 'data/processed/fraud_data_processed.csv'
  drop_columns: ['Dummy Policy No','Bank code']
  money_columns: ['POLICY SUMASSURED','Premium','Annual Income']
  missing_value: -1
  label_encoding: true
  scaling_method: StandardScaler  # or MinMaxScaler

logging:
  level: INFO
  file: 'logs/app.log'

rf_model:
  test_size: 0.4
  random_state: 30
  cv_folds: 3
  param_grid:
    n_estimators: [50, 100,200]
    max_depth: [5, 10, None]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 2]
    class_weight: ["balanced"]